[package]
name = "happy"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies]
serde = "*"
serde_json = "*"
futures = "*"
hyper = "*"
hyper-router = "*"
regex = "*"
combine = "*"
mime = "*"
mime_guess = "2.0.0-alpha.1"
void = "*"

[dev-dependencies]
serde_derive = "*"
